### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by anurbol** [Sneezry/vscode-version-watcher#2]
Hey, Zhe Li. This is a **great** repo! It is so needed for native Node.js addons for VSCode building. 
See [this issue](https://github.com/microsoft/vscode/issues/85939). However, it doesn't seem to work anymore. Do you know the reason? I am reviewing the code currently, but it would be so great if you could check what's wrong with it. Thanks!

**Comment by anurbol** [comment]
Seems like this URI https://raw.githubusercontent.com/electron/electron/6.5.1/atom/common/chrome_version.h doesn't work anymore (404).

**Comment by KamasamaK** [comment]
The last commit on 06/03/2019 failed compiling the TypeScript and hasn't run since.
https://travis-ci.org/Sneezry/vscode-version-watcher/builds/619859369

**Comment by Sneezry** [comment]
It wakes up :-)

**Comment by anurbol** [comment]
@Sneezry Great!!! Thank you! I hope people will notice and join this project more.
